export const OPEN_WEATHER_MAP_API_KEY = '7eccd585e6e215567bccd9354d4db8e6'
export enum OPEN_WEATHER_MAP_LANGUAGES {
  af = 'af',
  al = 'al',
  ar = 'ar',
  az = 'az',
  bg = 'bg',
  ca = 'ca',
  cz = 'cz',
  da = 'da',
  de = 'de',
  el = 'el',
  en = 'en',
  eu = 'eu',
  fa = 'fa',
  fi = 'fi',
  fr = 'fr',
  gl = 'gl',
  he = 'he',
  hi = 'hi',
  hr = 'hr',
  hu = 'hu',
  id = 'id',
  it = 'it',
  ja = 'ja',
  kr = 'kr',
  la = 'la',
  lt = 'lt',
  mk = 'mk',
  no = 'no',
  nl = 'nl',
  pl = 'pl',
  pt = 'pt',
  pt_br = 'pt_br',
  ro = 'ro',
  ru = 'ru',
  sv = 'sv',
  sk = 'sk',
  sl = 'sl',
  sp = 'sp',
  sr = 'sr',
  th = 'th',
  tr = 'tr',
  ua = 'ua',
  vi = 'vi',
  zh_cn = 'zh_cn',
  zh_tw = 'zh_tw',
  zu = 'zu',
}

type LanguageMap<T extends string> = {
  [key in T]: string
}

const languageArray = Object.values(OPEN_WEATHER_MAP_LANGUAGES) as Array<
  keyof typeof OPEN_WEATHER_MAP_LANGUAGES
>

export interface OpenWeatherMapLanguage
  extends LanguageMap<(typeof languageArray)[number]> {}

export const languages: OpenWeatherMapLanguage = {
  af: 'Afrikaans',
  al: 'Albanian',
  ar: 'Arabic',
  az: 'Azerbaijani',
  bg: 'Bulgarian',
  ca: 'Catalan',
  cz: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  eu: 'Basque',
  fa: 'Persian (Farsi)',
  fi: 'Finnish',
  fr: 'French',
  gl: 'Galician',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  kr: 'Korean',
  la: 'Latvian',
  lt: 'Lithuanian',
  mk: 'Macedonian',
  no: 'Norwegian',
  nl: 'Dutch',
  pl: 'Polish',
  pt: 'Portuguese',
  pt_br: 'Português Brasil',
  ro: 'Romanian',
  ru: 'Russian',
  sv: 'Swedish',
  sk: 'Slovak',
  sl: 'Slovenian',
  sp: 'Spanish',
  sr: 'Serbian',
  th: 'Thai',
  tr: 'Turkish',
  ua: 'Ukrainian',
  vi: 'Vietnamese',
  zh_cn: 'Chinese Simplified',
  zh_tw: 'Chinese Traditional',
  zu: 'Zulu',
}
